import type { AppLanguage } from "../settings/regionalPrefs";

export type AuthMessages = {
  signInTitle: string;
  emailOrUsername: string;
  password: string;
  forgotPasswordOrUsername: string;
  passwordLink: string;
  usernameLink: string;
  continue: string;
  or: string;
  signInWithGoogle: string;
  signInWithX: string;
  noAccount: string;
  signUpLink: string;
  createAccount: string;
  createAccountTitle: string;
  signUpSubtitle: string;
  email: string;
  signUpWithGoogle: string;
  signUpWithX: string;
  hasAccount: string;
  signInLink: string;
  verifyEmailBlurb: string;
  verificationCode: string;
  verifyEmail: string;
  useDifferentEmail: string;
  forgotTitle: string;
  forgotBlurb: string;
  forgotResetBlurb: string;
  sendEmail: string;
  resetCode: string;
  newPassword: string;
  resetPassword: string;
  checkEmailForCode: string;
  back: string;
  contactSupport: string;
  privacyNotice: string;
  termsOfService: string;
  showPassword: string;
  hidePassword: string;
  language: string;
  needsSecondFactor: string;
  couldntSignIn: string;
  couldntVerify: string;
  couldntReset: string;
  yourEmail: string;
};

export type AuthMessageKey = keyof AuthMessages;

const enUS: AuthMessages = {
  "signInTitle": "Sign in to Pioni",
  "emailOrUsername": "Email or username",
  "password": "Password",
  "forgotPasswordOrUsername": "Forgot {password} or {username}?",
  "passwordLink": "password",
  "usernameLink": "username",
  "continue": "Continue",
  "or": "Or",
  "signInWithGoogle": "Sign in with Google",
  "signInWithX": "Sign in with X",
  "noAccount": "Don't have an account?",
  "signUpLink": "Sign up",
  "createAccount": "Create account",
  "createAccountTitle": "Create an account",
  "signUpSubtitle": "Paper trading on Pioni",
  "email": "Email",
  "signUpWithGoogle": "Sign up with Google",
  "signUpWithX": "Sign up with X",
  "hasAccount": "Already have an account?",
  "signInLink": "Sign in",
  "verifyEmailBlurb": "Enter the verification code we sent to {email}.",
  "verificationCode": "Verification code",
  "verifyEmail": "Verify email",
  "useDifferentEmail": "Use a different email",
  "forgotTitle": "Forgot password",
  "forgotBlurb": "Enter your email. If it matches an account, we'll send reset instructions.",
  "forgotResetBlurb": "Enter the code from your email and choose a new password.",
  "sendEmail": "Send email",
  "resetCode": "Reset code",
  "newPassword": "New password",
  "resetPassword": "Reset password",
  "checkEmailForCode": "Check your email for a reset code",
  "back": "Back",
  "contactSupport": "Contact support",
  "privacyNotice": "Privacy notice",
  "termsOfService": "Terms of service",
  "showPassword": "Show password",
  "hidePassword": "Hide password",
  "language": "Language",
  "needsSecondFactor": "Complete another verification step",
  "couldntSignIn": "Couldn't sign in",
  "couldntVerify": "Couldn't verify email",
  "couldntReset": "Couldn't reset password",
  "yourEmail": "your email"
};

export const AUTH_CATALOG: Record<AppLanguage, AuthMessages> = {
  "en-US": {
    "signInTitle": "Sign in to Pioni",
    "emailOrUsername": "Email or username",
    "password": "Password",
    "forgotPasswordOrUsername": "Forgot {password} or {username}?",
    "passwordLink": "password",
    "usernameLink": "username",
    "continue": "Continue",
    "or": "Or",
    "signInWithGoogle": "Sign in with Google",
    "signInWithX": "Sign in with X",
    "noAccount": "Don't have an account?",
    "signUpLink": "Sign up",
    "createAccount": "Create account",
    "createAccountTitle": "Create an account",
    "signUpSubtitle": "Paper trading on Pioni",
    "email": "Email",
    "signUpWithGoogle": "Sign up with Google",
    "signUpWithX": "Sign up with X",
    "hasAccount": "Already have an account?",
    "signInLink": "Sign in",
    "verifyEmailBlurb": "Enter the verification code we sent to {email}.",
    "verificationCode": "Verification code",
    "verifyEmail": "Verify email",
    "useDifferentEmail": "Use a different email",
    "forgotTitle": "Forgot password",
    "forgotBlurb": "Enter your email. If it matches an account, we'll send reset instructions.",
    "forgotResetBlurb": "Enter the code from your email and choose a new password.",
    "sendEmail": "Send email",
    "resetCode": "Reset code",
    "newPassword": "New password",
    "resetPassword": "Reset password",
    "checkEmailForCode": "Check your email for a reset code",
    "back": "Back",
    "contactSupport": "Contact support",
    "privacyNotice": "Privacy notice",
    "termsOfService": "Terms of service",
    "showPassword": "Show password",
    "hidePassword": "Hide password",
    "language": "Language",
    "needsSecondFactor": "Complete another verification step",
    "couldntSignIn": "Couldn't sign in",
    "couldntVerify": "Couldn't verify email",
    "couldntReset": "Couldn't reset password",
    "yourEmail": "your email"
  },
  "en-AU": {
    "signInTitle": "Sign in to Pioni",
    "emailOrUsername": "Email or username",
    "password": "Password",
    "forgotPasswordOrUsername": "Forgot {password} or {username}?",
    "passwordLink": "password",
    "usernameLink": "username",
    "continue": "Continue",
    "or": "Or",
    "signInWithGoogle": "Sign in with Google",
    "signInWithX": "Sign in with X",
    "noAccount": "Don't have an account?",
    "signUpLink": "Sign up",
    "createAccount": "Create Account",
    "createAccountTitle": "Create an account",
    "signUpSubtitle": "Access paper trading on Pioni",
    "email": "Email",
    "signUpWithGoogle": "Sign up with Google",
    "signUpWithX": "Sign up with X",
    "hasAccount": "Already have an account?",
    "signInLink": "Sign in",
    "verifyEmailBlurb": "Enter the verification code we sent to {email}.",
    "verificationCode": "Verification code",
    "verifyEmail": "Verify email",
    "useDifferentEmail": "Use a different email",
    "forgotTitle": "Forgot password",
    "forgotBlurb": "Enter your email address. If it's correct, we'll send you an email with password reset instructions.",
    "forgotResetBlurb": "Enter the code from your email and choose a new password.",
    "sendEmail": "Send email",
    "resetCode": "Reset code",
    "newPassword": "New password",
    "resetPassword": "Reset password",
    "checkEmailForCode": "Check your email for a reset code",
    "back": "Back",
    "contactSupport": "Contact Support",
    "privacyNotice": "Privacy Notice",
    "termsOfService": "Terms of Service",
    "showPassword": "Show password",
    "hidePassword": "Hide password",
    "language": "Language",
    "needsSecondFactor": "Additional verification is required for this account",
    "couldntSignIn": "Couldn't complete sign in. Try again",
    "couldntVerify": "Couldn't verify email. Try again",
    "couldntReset": "Couldn't reset password. Try again",
    "yourEmail": "your email"
  },
  "en-CA": {
    "signInTitle": "Sign in to Pioni",
    "emailOrUsername": "Email or username",
    "password": "Password",
    "forgotPasswordOrUsername": "Forgot {password} or {username}?",
    "passwordLink": "password",
    "usernameLink": "username",
    "continue": "Continue",
    "or": "Or",
    "signInWithGoogle": "Sign in with Google",
    "signInWithX": "Sign in with X",
    "noAccount": "Don't have an account?",
    "signUpLink": "Sign up",
    "createAccount": "Create Account",
    "createAccountTitle": "Create an account",
    "signUpSubtitle": "Access paper trading on Pioni",
    "email": "Email",
    "signUpWithGoogle": "Sign up with Google",
    "signUpWithX": "Sign up with X",
    "hasAccount": "Already have an account?",
    "signInLink": "Sign in",
    "verifyEmailBlurb": "Enter the verification code we sent to {email}.",
    "verificationCode": "Verification code",
    "verifyEmail": "Verify email",
    "useDifferentEmail": "Use a different email",
    "forgotTitle": "Forgot password",
    "forgotBlurb": "Enter your email address. If it's correct, we'll send you an email with password reset instructions.",
    "forgotResetBlurb": "Enter the code from your email and choose a new password.",
    "sendEmail": "Send email",
    "resetCode": "Reset code",
    "newPassword": "New password",
    "resetPassword": "Reset password",
    "checkEmailForCode": "Check your email for a reset code",
    "back": "Back",
    "contactSupport": "Contact Support",
    "privacyNotice": "Privacy Notice",
    "termsOfService": "Terms of Service",
    "showPassword": "Show password",
    "hidePassword": "Hide password",
    "language": "Language",
    "needsSecondFactor": "Additional verification is required for this account",
    "couldntSignIn": "Couldn't complete sign in. Try again",
    "couldntVerify": "Couldn't verify email. Try again",
    "couldntReset": "Couldn't reset password. Try again",
    "yourEmail": "your email"
  },
  "en-GB": {
    "signInTitle": "Sign in to Pioni",
    "emailOrUsername": "Email or username",
    "password": "Password",
    "forgotPasswordOrUsername": "Forgot {password} or {username}?",
    "passwordLink": "password",
    "usernameLink": "username",
    "continue": "Continue",
    "or": "Or",
    "signInWithGoogle": "Sign in with Google",
    "signInWithX": "Sign in with X",
    "noAccount": "Don't have an account?",
    "signUpLink": "Sign up",
    "createAccount": "Create Account",
    "createAccountTitle": "Create an account",
    "signUpSubtitle": "Access paper trading on Pioni",
    "email": "Email",
    "signUpWithGoogle": "Sign up with Google",
    "signUpWithX": "Sign up with X",
    "hasAccount": "Already have an account?",
    "signInLink": "Sign in",
    "verifyEmailBlurb": "Enter the verification code we sent to {email}.",
    "verificationCode": "Verification code",
    "verifyEmail": "Verify email",
    "useDifferentEmail": "Use a different email",
    "forgotTitle": "Forgot password",
    "forgotBlurb": "Enter your email address. If it's correct, we'll send you an email with password reset instructions.",
    "forgotResetBlurb": "Enter the code from your email and choose a new password.",
    "sendEmail": "Send email",
    "resetCode": "Reset code",
    "newPassword": "New password",
    "resetPassword": "Reset password",
    "checkEmailForCode": "Check your email for a reset code",
    "back": "Back",
    "contactSupport": "Contact Support",
    "privacyNotice": "Privacy Notice",
    "termsOfService": "Terms of Service",
    "showPassword": "Show password",
    "hidePassword": "Hide password",
    "language": "Language",
    "needsSecondFactor": "Additional verification is required for this account",
    "couldntSignIn": "Couldn't complete sign in. Try again",
    "couldntVerify": "Couldn't verify email. Try again",
    "couldntReset": "Couldn't reset password. Try again",
    "yourEmail": "your email"
  },
  "de-DE": {
    "signInTitle": "Bei Pioni anmelden",
    "emailOrUsername": "E-Mail-Adresse oder Benutzername",
    "password": "Passwort",
    "forgotPasswordOrUsername": "{password} oder {username} vergessen?",
    "passwordLink": "Passwort",
    "usernameLink": "Benutzernamen",
    "continue": "Fortfahren",
    "or": "Oder",
    "signInWithGoogle": "Mit Google anmelden",
    "signInWithX": "Mit X anmelden",
    "noAccount": "Du hast noch kein Konto?",
    "signUpLink": "Registrieren",
    "createAccount": "Registrieren",
    "createAccountTitle": "Konto erstellen",
    "signUpSubtitle": "Zugang zum Paper-Trading auf Pioni",
    "email": "E-Mail",
    "signUpWithGoogle": "Mit Google registrieren",
    "signUpWithX": "Mit X registrieren",
    "hasAccount": "Du hast bereits ein Konto?",
    "signInLink": "Anmelden",
    "verifyEmailBlurb": "Gib den Bestätigungscode ein, den wir an {email} gesendet haben.",
    "verificationCode": "Bestätigungscode",
    "verifyEmail": "E-Mail bestätigen",
    "useDifferentEmail": "Andere E-Mail verwenden",
    "forgotTitle": "Passwort vergessen",
    "forgotBlurb": "Gib deine E-Mail-Adresse ein. Wenn sie korrekt ist, senden wir dir eine E-Mail mit Anweisungen zum Zurücksetzen deines Passworts.",
    "forgotResetBlurb": "Gib den Code aus deiner E-Mail ein und wähle ein neues Passwort.",
    "sendEmail": "E-Mail senden",
    "resetCode": "Reset-Code",
    "newPassword": "Neues Passwort",
    "resetPassword": "Passwort zurücksetzen",
    "checkEmailForCode": "Prüfe deine E-Mail auf einen Reset-Code",
    "back": "Zurück",
    "contactSupport": "Support kontaktieren",
    "privacyNotice": "Datenschutzerklärung",
    "termsOfService": "Nutzungsbedingungen",
    "showPassword": "Passwort anzeigen",
    "hidePassword": "Passwort verbergen",
    "language": "Sprache",
    "needsSecondFactor": "Für dieses Konto ist eine zusätzliche Bestätigung erforderlich",
    "couldntSignIn": "Anmeldung fehlgeschlagen. Bitte erneut versuchen",
    "couldntVerify": "E-Mail konnte nicht bestätigt werden. Bitte erneut versuchen",
    "couldntReset": "Passwort konnte nicht zurückgesetzt werden. Bitte erneut versuchen",
    "yourEmail": "deine E-Mail"
  },
  "fr-FR": {
    "signInTitle": "Connexion à Pioni",
    "emailOrUsername": "E-mail ou nom d'utilisateur",
    "password": "Mot de passe",
    "forgotPasswordOrUsername": "{password} ou {username} oublié ?",
    "passwordLink": "Mot de passe",
    "usernameLink": "nom d'utilisateur",
    "continue": "Continuer",
    "or": "Ou",
    "signInWithGoogle": "Se connecter avec Google",
    "signInWithX": "Se connecter avec X",
    "noAccount": "Vous n'avez pas de compte ?",
    "signUpLink": "S'inscrire",
    "createAccount": "Créer un compte",
    "createAccountTitle": "Créer un compte",
    "signUpSubtitle": "Accédez au paper trading sur Pioni",
    "email": "E-mail",
    "signUpWithGoogle": "S'inscrire avec Google",
    "signUpWithX": "S'inscrire avec X",
    "hasAccount": "Vous avez déjà un compte ?",
    "signInLink": "Se connecter",
    "verifyEmailBlurb": "Saisissez le code de vérification que nous avons envoyé à {email}.",
    "verificationCode": "Code de vérification",
    "verifyEmail": "Vérifier l'e-mail",
    "useDifferentEmail": "Utiliser une autre adresse e-mail",
    "forgotTitle": "Mot de passe oublié",
    "forgotBlurb": "Saisissez votre adresse e-mail. Si elle est correcte, nous vous enverrons un e-mail avec les instructions de réinitialisation.",
    "forgotResetBlurb": "Saisissez le code reçu par e-mail et choisissez un nouveau mot de passe.",
    "sendEmail": "Envoyer l'e-mail",
    "resetCode": "Code de réinitialisation",
    "newPassword": "Nouveau mot de passe",
    "resetPassword": "Réinitialiser le mot de passe",
    "checkEmailForCode": "Vérifiez votre e-mail pour un code de réinitialisation",
    "back": "Retour",
    "contactSupport": "Contacter le support",
    "privacyNotice": "Avis de confidentialité",
    "termsOfService": "Conditions d'utilisation",
    "showPassword": "Afficher le mot de passe",
    "hidePassword": "Masquer le mot de passe",
    "language": "Langue",
    "needsSecondFactor": "Une vérification supplémentaire est requise pour ce compte",
    "couldntSignIn": "Impossible de se connecter. Réessayez",
    "couldntVerify": "Impossible de vérifier l'e-mail. Réessayez",
    "couldntReset": "Impossible de réinitialiser le mot de passe. Réessayez",
    "yourEmail": "votre e-mail"
  },
  "es-ES": {
    "signInTitle": "Iniciar sesión en Pioni",
    "emailOrUsername": "Correo o nombre de usuario",
    "password": "Contraseña",
    "forgotPasswordOrUsername": "¿Has olvidado la {password} o el {username}?",
    "passwordLink": "contraseña",
    "usernameLink": "nombre de usuario",
    "continue": "Continuar",
    "or": "O",
    "signInWithGoogle": "Iniciar sesión con Google",
    "signInWithX": "Iniciar sesión con X",
    "noAccount": "¿No tienes una cuenta?",
    "signUpLink": "Regístrate",
    "createAccount": "Crear cuenta",
    "createAccountTitle": "Crear una cuenta",
    "signUpSubtitle": "Accede al paper trading en Pioni",
    "email": "Correo",
    "signUpWithGoogle": "Registrarse con Google",
    "signUpWithX": "Registrarse con X",
    "hasAccount": "¿Ya tienes una cuenta?",
    "signInLink": "Iniciar sesión",
    "verifyEmailBlurb": "Introduce el código de verificación que enviamos a {email}.",
    "verificationCode": "Código de verificación",
    "verifyEmail": "Verificar correo",
    "useDifferentEmail": "Usar otro correo",
    "forgotTitle": "Olvidé la contraseña",
    "forgotBlurb": "Introduce tu dirección de correo. Si es correcta, te enviaremos un correo con instrucciones para restablecer la contraseña.",
    "forgotResetBlurb": "Introduce el código de tu correo y elige una nueva contraseña.",
    "sendEmail": "Enviar correo",
    "resetCode": "Código de restablecimiento",
    "newPassword": "Nueva contraseña",
    "resetPassword": "Restablecer contraseña",
    "checkEmailForCode": "Revisa tu correo para obtener un código de restablecimiento",
    "back": "Atrás",
    "contactSupport": "Contactar con soporte",
    "privacyNotice": "Aviso de privacidad",
    "termsOfService": "Términos del servicio",
    "showPassword": "Mostrar contraseña",
    "hidePassword": "Ocultar contraseña",
    "language": "Idioma",
    "needsSecondFactor": "Se requiere una verificación adicional para esta cuenta",
    "couldntSignIn": "No se pudo iniciar sesión. Inténtalo de nuevo",
    "couldntVerify": "No se pudo verificar el correo. Inténtalo de nuevo",
    "couldntReset": "No se pudo restablecer la contraseña. Inténtalo de nuevo",
    "yourEmail": "tu correo"
  },
  "es-AR": {
    "signInTitle": "Iniciar sesión en Pioni",
    "emailOrUsername": "Correo o nombre de usuario",
    "password": "Contraseña",
    "forgotPasswordOrUsername": "¿Has olvidado la {password} o el {username}?",
    "passwordLink": "contraseña",
    "usernameLink": "nombre de usuario",
    "continue": "Continuar",
    "or": "O",
    "signInWithGoogle": "Iniciar sesión con Google",
    "signInWithX": "Iniciar sesión con X",
    "noAccount": "¿No tienes una cuenta?",
    "signUpLink": "Regístrate",
    "createAccount": "Crear cuenta",
    "createAccountTitle": "Crear una cuenta",
    "signUpSubtitle": "Accede al paper trading en Pioni",
    "email": "Correo",
    "signUpWithGoogle": "Registrarse con Google",
    "signUpWithX": "Registrarse con X",
    "hasAccount": "¿Ya tienes una cuenta?",
    "signInLink": "Iniciar sesión",
    "verifyEmailBlurb": "Introduce el código de verificación que enviamos a {email}.",
    "verificationCode": "Código de verificación",
    "verifyEmail": "Verificar correo",
    "useDifferentEmail": "Usar otro correo",
    "forgotTitle": "Olvidé mi contraseña",
    "forgotBlurb": "Introduce tu dirección de correo. Si es correcta, te enviaremos un correo con instrucciones para restablecer la contraseña.",
    "forgotResetBlurb": "Introduce el código de tu correo y elige una nueva contraseña.",
    "sendEmail": "Enviar correo",
    "resetCode": "Código de restablecimiento",
    "newPassword": "Nueva contraseña",
    "resetPassword": "Restablecer contraseña",
    "checkEmailForCode": "Revisa tu correo para obtener un código de restablecimiento",
    "back": "Atrás",
    "contactSupport": "Contactar con soporte",
    "privacyNotice": "Aviso de privacidad",
    "termsOfService": "Términos del servicio",
    "showPassword": "Mostrar contraseña",
    "hidePassword": "Ocultar contraseña",
    "language": "Idioma",
    "needsSecondFactor": "Se requiere una verificación adicional para esta cuenta",
    "couldntSignIn": "No se pudo iniciar sesión. Inténtalo de nuevo",
    "couldntVerify": "No se pudo verificar el correo. Inténtalo de nuevo",
    "couldntReset": "No se pudo restablecer la contraseña. Inténtalo de nuevo",
    "yourEmail": "tu correo"
  },
  "es-419": {
    "signInTitle": "Iniciar sesión en Pioni",
    "emailOrUsername": "Correo o nombre de usuario",
    "password": "Contraseña",
    "forgotPasswordOrUsername": "¿Has olvidado la {password} o el {username}?",
    "passwordLink": "contraseña",
    "usernameLink": "nombre de usuario",
    "continue": "Continuar",
    "or": "O",
    "signInWithGoogle": "Iniciar sesión con Google",
    "signInWithX": "Iniciar sesión con X",
    "noAccount": "¿No tienes una cuenta?",
    "signUpLink": "Regístrate",
    "createAccount": "Crear cuenta",
    "createAccountTitle": "Crear una cuenta",
    "signUpSubtitle": "Accede al paper trading en Pioni",
    "email": "Correo",
    "signUpWithGoogle": "Registrarse con Google",
    "signUpWithX": "Registrarse con X",
    "hasAccount": "¿Ya tienes una cuenta?",
    "signInLink": "Iniciar sesión",
    "verifyEmailBlurb": "Introduce el código de verificación que enviamos a {email}.",
    "verificationCode": "Código de verificación",
    "verifyEmail": "Verificar correo",
    "useDifferentEmail": "Usar otro correo",
    "forgotTitle": "Olvidé mi contraseña",
    "forgotBlurb": "Introduce tu dirección de correo. Si es correcta, te enviaremos un correo con instrucciones para restablecer la contraseña.",
    "forgotResetBlurb": "Introduce el código de tu correo y elige una nueva contraseña.",
    "sendEmail": "Enviar correo",
    "resetCode": "Código de restablecimiento",
    "newPassword": "Nueva contraseña",
    "resetPassword": "Restablecer contraseña",
    "checkEmailForCode": "Revisa tu correo para obtener un código de restablecimiento",
    "back": "Atrás",
    "contactSupport": "Contactar con soporte",
    "privacyNotice": "Aviso de privacidad",
    "termsOfService": "Términos del servicio",
    "showPassword": "Mostrar contraseña",
    "hidePassword": "Ocultar contraseña",
    "language": "Idioma",
    "needsSecondFactor": "Se requiere una verificación adicional para esta cuenta",
    "couldntSignIn": "No se pudo iniciar sesión. Inténtalo de nuevo",
    "couldntVerify": "No se pudo verificar el correo. Inténtalo de nuevo",
    "couldntReset": "No se pudo restablecer la contraseña. Inténtalo de nuevo",
    "yourEmail": "tu correo"
  },
  "es-MX": {
    "signInTitle": "Iniciar sesión en Pioni",
    "emailOrUsername": "Correo o nombre de usuario",
    "password": "Contraseña",
    "forgotPasswordOrUsername": "¿Has olvidado la {password} o el {username}?",
    "passwordLink": "contraseña",
    "usernameLink": "nombre de usuario",
    "continue": "Continuar",
    "or": "O",
    "signInWithGoogle": "Iniciar sesión con Google",
    "signInWithX": "Iniciar sesión con X",
    "noAccount": "¿No tienes una cuenta?",
    "signUpLink": "Regístrate",
    "createAccount": "Crear cuenta",
    "createAccountTitle": "Crear una cuenta",
    "signUpSubtitle": "Accede al paper trading en Pioni",
    "email": "Correo",
    "signUpWithGoogle": "Registrarse con Google",
    "signUpWithX": "Registrarse con X",
    "hasAccount": "¿Ya tienes una cuenta?",
    "signInLink": "Iniciar sesión",
    "verifyEmailBlurb": "Introduce el código de verificación que enviamos a {email}.",
    "verificationCode": "Código de verificación",
    "verifyEmail": "Verificar correo",
    "useDifferentEmail": "Usar otro correo",
    "forgotTitle": "Olvidé mi contraseña",
    "forgotBlurb": "Introduce tu dirección de correo. Si es correcta, te enviaremos un correo con instrucciones para restablecer la contraseña.",
    "forgotResetBlurb": "Introduce el código de tu correo y elige una nueva contraseña.",
    "sendEmail": "Enviar correo",
    "resetCode": "Código de restablecimiento",
    "newPassword": "Nueva contraseña",
    "resetPassword": "Restablecer contraseña",
    "checkEmailForCode": "Revisa tu correo para obtener un código de restablecimiento",
    "back": "Atrás",
    "contactSupport": "Contactar con soporte",
    "privacyNotice": "Aviso de privacidad",
    "termsOfService": "Términos del servicio",
    "showPassword": "Mostrar contraseña",
    "hidePassword": "Ocultar contraseña",
    "language": "Idioma",
    "needsSecondFactor": "Se requiere una verificación adicional para esta cuenta",
    "couldntSignIn": "No se pudo iniciar sesión. Inténtalo de nuevo",
    "couldntVerify": "No se pudo verificar el correo. Inténtalo de nuevo",
    "couldntReset": "No se pudo restablecer la contraseña. Inténtalo de nuevo",
    "yourEmail": "tu correo"
  },
  "it-IT": {
    "signInTitle": "Accedi a Pioni",
    "emailOrUsername": "Email o nome utente",
    "password": "Password",
    "forgotPasswordOrUsername": "Hai dimenticato la {password} o il {username}?",
    "passwordLink": "password",
    "usernameLink": "nome utente",
    "continue": "Continua",
    "or": "Oppure",
    "signInWithGoogle": "Accedi con Google",
    "signInWithX": "Accedi con X",
    "noAccount": "Non hai un account?",
    "signUpLink": "Registrati",
    "createAccount": "Crea account",
    "createAccountTitle": "Crea un account",
    "signUpSubtitle": "Accedi al paper trading su Pioni",
    "email": "Email",
    "signUpWithGoogle": "Registrati con Google",
    "signUpWithX": "Registrati con X",
    "hasAccount": "Hai già un account?",
    "signInLink": "Accedi",
    "verifyEmailBlurb": "Inserisci il codice di verifica inviato a {email}.",
    "verificationCode": "Codice di verifica",
    "verifyEmail": "Verifica email",
    "useDifferentEmail": "Usa un'email diversa",
    "forgotTitle": "Password dimenticata",
    "forgotBlurb": "Inserisci il tuo indirizzo email. Se è corretto, ti invieremo un'email con le istruzioni per reimpostare la password.",
    "forgotResetBlurb": "Inserisci il codice ricevuto via email e scegli una nuova password.",
    "sendEmail": "Invia email",
    "resetCode": "Codice di reset",
    "newPassword": "Nuova password",
    "resetPassword": "Reimposta password",
    "checkEmailForCode": "Controlla la tua email per un codice di reset",
    "back": "Indietro",
    "contactSupport": "Contatta il supporto",
    "privacyNotice": "Informativa sulla privacy",
    "termsOfService": "Termini di servizio",
    "showPassword": "Mostra password",
    "hidePassword": "Nascondi password",
    "language": "Lingua",
    "needsSecondFactor": "Per questo account è richiesta un'ulteriore verifica",
    "couldntSignIn": "Impossibile completare l'accesso. Riprova",
    "couldntVerify": "Impossibile verificare l'email. Riprova",
    "couldntReset": "Impossibile reimpostare la password. Riprova",
    "yourEmail": "la tua email"
  },
  "nl-NL": {
    "signInTitle": "Inloggen bij Pioni",
    "emailOrUsername": "E-mail of gebruikersnaam",
    "password": "Wachtwoord",
    "forgotPasswordOrUsername": "{password} of {username} vergeten?",
    "passwordLink": "Wachtwoord",
    "usernameLink": "gebruikersnaam",
    "continue": "Doorgaan",
    "or": "Of",
    "signInWithGoogle": "Inloggen met Google",
    "signInWithX": "Inloggen met X",
    "noAccount": "Heb je nog geen account?",
    "signUpLink": "Registreren",
    "createAccount": "Account aanmaken",
    "createAccountTitle": "Account aanmaken",
    "signUpSubtitle": "Toegang tot paper trading op Pioni",
    "email": "E-mail",
    "signUpWithGoogle": "Registreren met Google",
    "signUpWithX": "Registreren met X",
    "hasAccount": "Heb je al een account?",
    "signInLink": "Inloggen",
    "verifyEmailBlurb": "Voer de verificatiecode in die we naar {email} hebben gestuurd.",
    "verificationCode": "Verificatiecode",
    "verifyEmail": "E-mail verifiëren",
    "useDifferentEmail": "Andere e-mail gebruiken",
    "forgotTitle": "Wachtwoord vergeten",
    "forgotBlurb": "Voer je e-mailadres in. Als het correct is, sturen we je een e-mail met instructies om je wachtwoord te resetten.",
    "forgotResetBlurb": "Voer de code uit je e-mail in en kies een nieuw wachtwoord.",
    "sendEmail": "E-mail verzenden",
    "resetCode": "Resetcode",
    "newPassword": "Nieuw wachtwoord",
    "resetPassword": "Wachtwoord resetten",
    "checkEmailForCode": "Controleer je e-mail voor een resetcode",
    "back": "Terug",
    "contactSupport": "Contact opnemen met support",
    "privacyNotice": "Privacyverklaring",
    "termsOfService": "Servicevoorwaarden",
    "showPassword": "Wachtwoord tonen",
    "hidePassword": "Wachtwoord verbergen",
    "language": "Taal",
    "needsSecondFactor": "Extra verificatie is vereist voor dit account",
    "couldntSignIn": "Inloggen mislukt. Probeer het opnieuw",
    "couldntVerify": "E-mail verifiëren mislukt. Probeer het opnieuw",
    "couldntReset": "Wachtwoord resetten mislukt. Probeer het opnieuw",
    "yourEmail": "je e-mail"
  },
  "pt-BR": {
    "signInTitle": "Entrar na Pioni",
    "emailOrUsername": "E-mail ou nome de usuário",
    "password": "Senha",
    "forgotPasswordOrUsername": "Esqueceu a {password} ou o {username}?",
    "passwordLink": "senha",
    "usernameLink": "nome de usuário",
    "continue": "Continuar",
    "or": "Ou",
    "signInWithGoogle": "Entrar com o Google",
    "signInWithX": "Entrar com o X",
    "noAccount": "Não tem uma conta?",
    "signUpLink": "Cadastre-se",
    "createAccount": "Criar conta",
    "createAccountTitle": "Criar uma conta",
    "signUpSubtitle": "Acesse o paper trading na Pioni",
    "email": "E-mail",
    "signUpWithGoogle": "Cadastrar com o Google",
    "signUpWithX": "Cadastrar com o X",
    "hasAccount": "Já tem uma conta?",
    "signInLink": "Entrar",
    "verifyEmailBlurb": "Digite o código de verificação que enviamos para {email}.",
    "verificationCode": "Código de verificação",
    "verifyEmail": "Verificar e-mail",
    "useDifferentEmail": "Usar outro e-mail",
    "forgotTitle": "Esqueci a senha",
    "forgotBlurb": "Digite seu endereço de e-mail. Se estiver correto, enviaremos um e-mail com instruções para redefinir a senha.",
    "forgotResetBlurb": "Digite o código do seu e-mail e escolha uma nova senha.",
    "sendEmail": "Enviar e-mail",
    "resetCode": "Código de redefinição",
    "newPassword": "Nova senha",
    "resetPassword": "Redefinir senha",
    "checkEmailForCode": "Verifique seu e-mail para obter um código de redefinição",
    "back": "Voltar",
    "contactSupport": "Falar com o suporte",
    "privacyNotice": "Aviso de privacidade",
    "termsOfService": "Termos de serviço",
    "showPassword": "Mostrar senha",
    "hidePassword": "Ocultar senha",
    "language": "Idioma",
    "needsSecondFactor": "É necessária uma verificação adicional para esta conta",
    "couldntSignIn": "Não foi possível concluir o login. Tente novamente",
    "couldntVerify": "Não foi possível verificar o e-mail. Tente novamente",
    "couldntReset": "Não foi possível redefinir a senha. Tente novamente",
    "yourEmail": "seu e-mail"
  },
  "pt-PT": {
    "signInTitle": "Entrar na Pioni",
    "emailOrUsername": "E-mail ou nome de utilizador",
    "password": "Senha",
    "forgotPasswordOrUsername": "Esqueceu a {password} ou o {username}?",
    "passwordLink": "senha",
    "usernameLink": "nome de utilizador",
    "continue": "Continuar",
    "or": "Ou",
    "signInWithGoogle": "Entrar com o Google",
    "signInWithX": "Entrar com o X",
    "noAccount": "Não tem uma conta?",
    "signUpLink": "Cadastre-se",
    "createAccount": "Criar conta",
    "createAccountTitle": "Criar uma conta",
    "signUpSubtitle": "Aceda ao paper trading na Pioni",
    "email": "E-mail",
    "signUpWithGoogle": "Cadastrar com o Google",
    "signUpWithX": "Cadastrar com o X",
    "hasAccount": "Já tem uma conta?",
    "signInLink": "Entrar",
    "verifyEmailBlurb": "Digite o código de verificação que enviamos para {email}.",
    "verificationCode": "Código de verificação",
    "verifyEmail": "Verificar e-mail",
    "useDifferentEmail": "Usar outro e-mail",
    "forgotTitle": "Esqueci a senha",
    "forgotBlurb": "Digite seu endereço de e-mail. Se estiver correto, enviaremos um e-mail com instruções para redefinir a senha.",
    "forgotResetBlurb": "Digite o código do seu e-mail e escolha uma nova senha.",
    "sendEmail": "Enviar e-mail",
    "resetCode": "Código de redefinição",
    "newPassword": "Nova senha",
    "resetPassword": "Redefinir senha",
    "checkEmailForCode": "Verifique seu e-mail para obter um código de redefinição",
    "back": "Voltar",
    "contactSupport": "Contactar o suporte",
    "privacyNotice": "Aviso de privacidade",
    "termsOfService": "Termos de serviço",
    "showPassword": "Mostrar senha",
    "hidePassword": "Ocultar senha",
    "language": "Idioma",
    "needsSecondFactor": "É necessária uma verificação adicional para esta conta",
    "couldntSignIn": "Não foi possível concluir o login. Tente novamente",
    "couldntVerify": "Não foi possível verificar o e-mail. Tente novamente",
    "couldntReset": "Não foi possível redefinir a senha. Tente novamente",
    "yourEmail": "seu e-mail"
  },
  "pl-PL": {
    "signInTitle": "Zaloguj się do Pioni",
    "emailOrUsername": "E-mail lub nazwa użytkownika",
    "password": "Hasło",
    "forgotPasswordOrUsername": "Nie pamiętasz {password} lub {username}?",
    "passwordLink": "hasła",
    "usernameLink": "nazwy użytkownika",
    "continue": "Kontynuuj",
    "or": "Lub",
    "signInWithGoogle": "Zaloguj się przez Google",
    "signInWithX": "Zaloguj się przez X",
    "noAccount": "Nie masz konta?",
    "signUpLink": "Zarejestruj się",
    "createAccount": "Utwórz konto",
    "createAccountTitle": "Utwórz konto",
    "signUpSubtitle": "Uzyskaj dostęp do paper tradingu w Pioni",
    "email": "E-mail",
    "signUpWithGoogle": "Zarejestruj się przez Google",
    "signUpWithX": "Zarejestruj się przez X",
    "hasAccount": "Masz już konto?",
    "signInLink": "Zaloguj się",
    "verifyEmailBlurb": "Wprowadź kod weryfikacyjny wysłany na {email}.",
    "verificationCode": "Kod weryfikacyjny",
    "verifyEmail": "Zweryfikuj e-mail",
    "useDifferentEmail": "Użyj innego e-maila",
    "forgotTitle": "Nie pamiętam hasła",
    "forgotBlurb": "Wprowadź swój adres e-mail. Jeśli jest poprawny, wyślemy e-mail z instrukcjami resetowania hasła.",
    "forgotResetBlurb": "Wprowadź kod z e-maila i wybierz nowe hasło.",
    "sendEmail": "Wyślij e-mail",
    "resetCode": "Kod resetowania",
    "newPassword": "Nowe hasło",
    "resetPassword": "Zresetuj hasło",
    "checkEmailForCode": "Sprawdź e-mail, aby otrzymać kod resetowania",
    "back": "Wstecz",
    "contactSupport": "Skontaktuj się z pomocą",
    "privacyNotice": "Informacja o prywatności",
    "termsOfService": "Warunki korzystania z usługi",
    "showPassword": "Pokaż hasło",
    "hidePassword": "Ukryj hasło",
    "language": "Język",
    "needsSecondFactor": "Dla tego konta wymagana jest dodatkowa weryfikacja",
    "couldntSignIn": "Nie udało się zalogować. Spróbuj ponownie",
    "couldntVerify": "Nie udało się zweryfikować e-maila. Spróbuj ponownie",
    "couldntReset": "Nie udało się zresetować hasła. Spróbuj ponownie",
    "yourEmail": "Twój e-mail"
  },
  "sv-SE": {
    "signInTitle": "Logga in på Pioni",
    "emailOrUsername": "E-post eller användarnamn",
    "password": "Lösenord",
    "forgotPasswordOrUsername": "Glömt {password} eller {username}?",
    "passwordLink": "lösenord",
    "usernameLink": "användarnamn",
    "continue": "Fortsätt",
    "or": "Eller",
    "signInWithGoogle": "Logga in med Google",
    "signInWithX": "Logga in med X",
    "noAccount": "Har du inget konto?",
    "signUpLink": "Registrera dig",
    "createAccount": "Skapa konto",
    "createAccountTitle": "Skapa ett konto",
    "signUpSubtitle": "Få tillgång till paper trading på Pioni",
    "email": "E-post",
    "signUpWithGoogle": "Registrera dig med Google",
    "signUpWithX": "Registrera dig med X",
    "hasAccount": "Har du redan ett konto?",
    "signInLink": "Logga in",
    "verifyEmailBlurb": "Ange verifieringskoden vi skickade till {email}.",
    "verificationCode": "Verifieringskod",
    "verifyEmail": "Verifiera e-post",
    "useDifferentEmail": "Använd en annan e-postadress",
    "forgotTitle": "Glömt lösenord",
    "forgotBlurb": "Ange din e-postadress. Om den är korrekt skickar vi ett e-postmeddelande med instruktioner för att återställa lösenordet.",
    "forgotResetBlurb": "Ange koden från din e-post och välj ett nytt lösenord.",
    "sendEmail": "Skicka e-post",
    "resetCode": "Återställningskod",
    "newPassword": "Nytt lösenord",
    "resetPassword": "Återställ lösenord",
    "checkEmailForCode": "Kontrollera din e-post för en återställningskod",
    "back": "Tillbaka",
    "contactSupport": "Kontakta support",
    "privacyNotice": "Integritetsmeddelande",
    "termsOfService": "Användarvillkor",
    "showPassword": "Visa lösenord",
    "hidePassword": "Dölj lösenord",
    "language": "Språk",
    "needsSecondFactor": "Ytterligare verifiering krävs för det här kontot",
    "couldntSignIn": "Kunde inte logga in. Försök igen",
    "couldntVerify": "Kunde inte verifiera e-post. Försök igen",
    "couldntReset": "Kunde inte återställa lösenord. Försök igen",
    "yourEmail": "din e-post"
  },
  "da-DK": {
    "signInTitle": "Log ind på Pioni",
    "emailOrUsername": "E-mail eller brugernavn",
    "password": "Adgangskode",
    "forgotPasswordOrUsername": "Glemt {password} eller {username}?",
    "passwordLink": "adgangskode",
    "usernameLink": "brugernavn",
    "continue": "Fortsæt",
    "or": "Eller",
    "signInWithGoogle": "Log ind med Google",
    "signInWithX": "Log ind med X",
    "noAccount": "Har du ikke en konto?",
    "signUpLink": "Tilmeld dig",
    "createAccount": "Opret konto",
    "createAccountTitle": "Opret en konto",
    "signUpSubtitle": "Få adgang til paper trading på Pioni",
    "email": "E-mail",
    "signUpWithGoogle": "Tilmeld dig med Google",
    "signUpWithX": "Tilmeld dig med X",
    "hasAccount": "Har du allerede en konto?",
    "signInLink": "Log ind",
    "verifyEmailBlurb": "Indtast den bekræftelseskode, vi sendte til {email}.",
    "verificationCode": "Bekræftelseskode",
    "verifyEmail": "Bekræft e-mail",
    "useDifferentEmail": "Brug en anden e-mail",
    "forgotTitle": "Glemt adgangskode",
    "forgotBlurb": "Indtast din e-mailadresse. Hvis den er korrekt, sender vi dig en e-mail med instruktioner til nulstilling af adgangskoden.",
    "forgotResetBlurb": "Indtast koden fra din e-mail, og vælg en ny adgangskode.",
    "sendEmail": "Send e-mail",
    "resetCode": "Nulstillingskode",
    "newPassword": "Ny adgangskode",
    "resetPassword": "Nulstil adgangskode",
    "checkEmailForCode": "Tjek din e-mail for en nulstillingskode",
    "back": "Tilbage",
    "contactSupport": "Kontakt support",
    "privacyNotice": "Privatlivserklæring",
    "termsOfService": "Servicevilkår",
    "showPassword": "Vis adgangskode",
    "hidePassword": "Skjul adgangskode",
    "language": "Sprog",
    "needsSecondFactor": "Yderligere bekræftelse er påkrævet for denne konto",
    "couldntSignIn": "Kunne ikke logge ind. Prøv igen",
    "couldntVerify": "Kunne ikke bekræfte e-mail. Prøv igen",
    "couldntReset": "Kunne ikke nulstille adgangskode. Prøv igen",
    "yourEmail": "din e-mail"
  },
  "nb-NO": {
    "signInTitle": "Logg inn på Pioni",
    "emailOrUsername": "E-post eller brukernavn",
    "password": "Passord",
    "forgotPasswordOrUsername": "Glemt {password} eller {username}?",
    "passwordLink": "passord",
    "usernameLink": "brukernavn",
    "continue": "Fortsett",
    "or": "Eller",
    "signInWithGoogle": "Logg inn med Google",
    "signInWithX": "Logg inn med X",
    "noAccount": "Har du ikke en konto?",
    "signUpLink": "Registrer deg",
    "createAccount": "Opprett konto",
    "createAccountTitle": "Opprett en konto",
    "signUpSubtitle": "Få tilgang til paper trading på Pioni",
    "email": "E-post",
    "signUpWithGoogle": "Registrer deg med Google",
    "signUpWithX": "Registrer deg med X",
    "hasAccount": "Har du allerede en konto?",
    "signInLink": "Logg inn",
    "verifyEmailBlurb": "Skriv inn bekreftelseskoden vi sendte til {email}.",
    "verificationCode": "Bekreftelseskode",
    "verifyEmail": "Bekreft e-post",
    "useDifferentEmail": "Bruk en annen e-post",
    "forgotTitle": "Glemt passord",
    "forgotBlurb": "Skriv inn e-postadressen din. Hvis den er riktig, sender vi deg en e-post med instruksjoner for å tilbakestille passordet.",
    "forgotResetBlurb": "Skriv inn koden fra e-posten din og velg et nytt passord.",
    "sendEmail": "Send e-post",
    "resetCode": "Tilbakestillingskode",
    "newPassword": "Nytt passord",
    "resetPassword": "Tilbakestill passord",
    "checkEmailForCode": "Sjekk e-posten din for en tilbakestillingskode",
    "back": "Tilbake",
    "contactSupport": "Kontakt support",
    "privacyNotice": "Personvernerklæring",
    "termsOfService": "Tjenestevilkår",
    "showPassword": "Vis passord",
    "hidePassword": "Skjul passord",
    "language": "Språk",
    "needsSecondFactor": "Ytterligere bekreftelse kreves for denne kontoen",
    "couldntSignIn": "Kunne ikke logge inn. Prøv igjen",
    "couldntVerify": "Kunne ikke bekrefte e-post. Prøv igjen",
    "couldntReset": "Kunne ikke tilbakestille passord. Prøv igjen",
    "yourEmail": "e-posten din"
  },
  "cs-CZ": {
    "signInTitle": "Přihlášení do Pioni",
    "emailOrUsername": "E-mail nebo uživatelské jméno",
    "password": "Heslo",
    "forgotPasswordOrUsername": "Zapomněli jste {password} nebo {username}?",
    "passwordLink": "heslo",
    "usernameLink": "uživatelské jméno",
    "continue": "Pokračovat",
    "or": "Nebo",
    "signInWithGoogle": "Přihlásit se přes Google",
    "signInWithX": "Přihlásit se přes X",
    "noAccount": "Nemáte účet?",
    "signUpLink": "Zaregistrovat se",
    "createAccount": "Vytvořit účet",
    "createAccountTitle": "Vytvořit účet",
    "signUpSubtitle": "Získejte přístup k paper tradingu na Pioni",
    "email": "E-mail",
    "signUpWithGoogle": "Registrovat se přes Google",
    "signUpWithX": "Registrovat se přes X",
    "hasAccount": "Už máte účet?",
    "signInLink": "Přihlásit se",
    "verifyEmailBlurb": "Zadejte ověřovací kód, který jsme poslali na {email}.",
    "verificationCode": "Ověřovací kód",
    "verifyEmail": "Ověřit e-mail",
    "useDifferentEmail": "Použít jiný e-mail",
    "forgotTitle": "Zapomenuté heslo",
    "forgotBlurb": "Zadejte svou e-mailovou adresu. Pokud je správná, pošleme vám e-mail s pokyny k obnovení hesla.",
    "forgotResetBlurb": "Zadejte kód z e-mailu a zvolte nové heslo.",
    "sendEmail": "Odeslat e-mail",
    "resetCode": "Obnovovací kód",
    "newPassword": "Nové heslo",
    "resetPassword": "Obnovit heslo",
    "checkEmailForCode": "Zkontrolujte e-mail kvůli obnovovacímu kódu",
    "back": "Zpět",
    "contactSupport": "Kontaktovat podporu",
    "privacyNotice": "Oznámení o ochraně osobních údajů",
    "termsOfService": "Smluvní podmínky",
    "showPassword": "Zobrazit heslo",
    "hidePassword": "Skrýt heslo",
    "language": "Jazyk",
    "needsSecondFactor": "Pro tento účet je vyžadováno další ověření",
    "couldntSignIn": "Přihlášení se nezdařilo. Zkuste to znovu",
    "couldntVerify": "E-mail se nepodařilo ověřit. Zkuste to znovu",
    "couldntReset": "Heslo se nepodařilo obnovit. Zkuste to znovu",
    "yourEmail": "váš e-mail"
  },
  "hu-HU": {
    "signInTitle": "Bejelentkezés a Pioni rendszerbe",
    "emailOrUsername": "E-mail vagy felhasználónév",
    "password": "Jelszó",
    "forgotPasswordOrUsername": "Elfelejtetted a {password}t vagy a {username}t?",
    "passwordLink": "jelszó",
    "usernameLink": "felhasználónév",
    "continue": "Folytatás",
    "or": "Vagy",
    "signInWithGoogle": "Bejelentkezés Google-lal",
    "signInWithX": "Bejelentkezés X-szel",
    "noAccount": "Nincs még fiókod?",
    "signUpLink": "Regisztráció",
    "createAccount": "Fiók létrehozása",
    "createAccountTitle": "Fiók létrehozása",
    "signUpSubtitle": "Hozzáférés a Pioni paper tradinghez",
    "email": "E-mail",
    "signUpWithGoogle": "Regisztráció Google-lal",
    "signUpWithX": "Regisztráció X-szel",
    "hasAccount": "Már van fiókod?",
    "signInLink": "Bejelentkezés",
    "verifyEmailBlurb": "Add meg a {email} címre küldött ellenőrző kódot.",
    "verificationCode": "Ellenőrző kód",
    "verifyEmail": "E-mail ellenőrzése",
    "useDifferentEmail": "Másik e-mail használata",
    "forgotTitle": "Elfelejtett jelszó",
    "forgotBlurb": "Add meg az e-mail-címed. Ha helyes, elküldjük a jelszó visszaállításához szükséges utasításokat.",
    "forgotResetBlurb": "Add meg az e-mailben kapott kódot, és válassz új jelszót.",
    "sendEmail": "E-mail küldése",
    "resetCode": "Visszaállítási kód",
    "newPassword": "Új jelszó",
    "resetPassword": "Jelszó visszaállítása",
    "checkEmailForCode": "Nézd meg az e-mailed a visszaállítási kódért",
    "back": "Vissza",
    "contactSupport": "Kapcsolat a támogatással",
    "privacyNotice": "Adatvédelmi tájékoztató",
    "termsOfService": "Szolgáltatási feltételek",
    "showPassword": "Jelszó megjelenítése",
    "hidePassword": "Jelszó elrejtése",
    "language": "Nyelv",
    "needsSecondFactor": "Ehhez a fiókhoz további ellenőrzés szükséges",
    "couldntSignIn": "A bejelentkezés nem sikerült. Próbáld újra",
    "couldntVerify": "Az e-mail ellenőrzése nem sikerült. Próbáld újra",
    "couldntReset": "A jelszó visszaállítása nem sikerült. Próbáld újra",
    "yourEmail": "az e-mailed"
  },
  "ro-RO": {
    "signInTitle": "Autentificare în Pioni",
    "emailOrUsername": "E-mail sau nume de utilizator",
    "password": "Parolă",
    "forgotPasswordOrUsername": "Ai uitat {password} sau {username}?",
    "passwordLink": "parola",
    "usernameLink": "numele de utilizator",
    "continue": "Continuă",
    "or": "Sau",
    "signInWithGoogle": "Autentificare cu Google",
    "signInWithX": "Autentificare cu X",
    "noAccount": "Nu ai un cont?",
    "signUpLink": "Înregistrează-te",
    "createAccount": "Creează cont",
    "createAccountTitle": "Creează un cont",
    "signUpSubtitle": "Accesează paper trading pe Pioni",
    "email": "E-mail",
    "signUpWithGoogle": "Înregistrare cu Google",
    "signUpWithX": "Înregistrare cu X",
    "hasAccount": "Ai deja un cont?",
    "signInLink": "Autentificare",
    "verifyEmailBlurb": "Introdu codul de verificare pe care l-am trimis la {email}.",
    "verificationCode": "Cod de verificare",
    "verifyEmail": "Verifică e-mailul",
    "useDifferentEmail": "Folosește alt e-mail",
    "forgotTitle": "Am uitat parola",
    "forgotBlurb": "Introdu adresa de e-mail. Dacă este corectă, îți vom trimite un e-mail cu instrucțiuni de resetare a parolei.",
    "forgotResetBlurb": "Introdu codul din e-mail și alege o parolă nouă.",
    "sendEmail": "Trimite e-mail",
    "resetCode": "Cod de resetare",
    "newPassword": "Parolă nouă",
    "resetPassword": "Resetează parola",
    "checkEmailForCode": "Verifică e-mailul pentru un cod de resetare",
    "back": "Înapoi",
    "contactSupport": "Contactează suportul",
    "privacyNotice": "Notificare de confidențialitate",
    "termsOfService": "Termeni și condiții",
    "showPassword": "Afișează parola",
    "hidePassword": "Ascunde parola",
    "language": "Limbă",
    "needsSecondFactor": "Este necesară o verificare suplimentară pentru acest cont",
    "couldntSignIn": "Nu s-a putut finaliza autentificarea. Încearcă din nou",
    "couldntVerify": "Nu s-a putut verifica e-mailul. Încearcă din nou",
    "couldntReset": "Nu s-a putut reseta parola. Încearcă din nou",
    "yourEmail": "e-mailul tău"
  },
  "tr-TR": {
    "signInTitle": "Pioni'ye giriş yap",
    "emailOrUsername": "E-posta veya kullanıcı adı",
    "password": "Şifre",
    "forgotPasswordOrUsername": "{password} veya {username} mı unuttunuz?",
    "passwordLink": "Şifrenizi",
    "usernameLink": "kullanıcı adınızı",
    "continue": "Devam",
    "or": "Veya",
    "signInWithGoogle": "Google ile giriş yap",
    "signInWithX": "X ile giriş yap",
    "noAccount": "Hesabınız yok mu?",
    "signUpLink": "Kaydol",
    "createAccount": "Hesap oluştur",
    "createAccountTitle": "Hesap oluştur",
    "signUpSubtitle": "Pioni'de paper trading'e erişin",
    "email": "E-posta",
    "signUpWithGoogle": "Google ile kaydol",
    "signUpWithX": "X ile kaydol",
    "hasAccount": "Zaten hesabınız var mı?",
    "signInLink": "Giriş yap",
    "verifyEmailBlurb": "{email} adresine gönderdiğimiz doğrulama kodunu girin.",
    "verificationCode": "Doğrulama kodu",
    "verifyEmail": "E-postayı doğrula",
    "useDifferentEmail": "Farklı bir e-posta kullan",
    "forgotTitle": "Şifremi unuttum",
    "forgotBlurb": "E-posta adresinizi girin. Doğruysa, şifre sıfırlama talimatlarını içeren bir e-posta göndeririz.",
    "forgotResetBlurb": "E-postanızdaki kodu girin ve yeni bir şifre seçin.",
    "sendEmail": "E-posta gönder",
    "resetCode": "Sıfırlama kodu",
    "newPassword": "Yeni şifre",
    "resetPassword": "Şifreyi sıfırla",
    "checkEmailForCode": "Sıfırlama kodu için e-postanızı kontrol edin",
    "back": "Geri",
    "contactSupport": "Destek ile iletişime geç",
    "privacyNotice": "Gizlilik bildirimi",
    "termsOfService": "Hizmet şartları",
    "showPassword": "Şifreyi göster",
    "hidePassword": "Şifreyi gizle",
    "language": "Dil",
    "needsSecondFactor": "Bu hesap için ek doğrulama gerekli",
    "couldntSignIn": "Giriş tamamlanamadı. Tekrar deneyin",
    "couldntVerify": "E-posta doğrulanamadı. Tekrar deneyin",
    "couldntReset": "Şifre sıfırlanamadı. Tekrar deneyin",
    "yourEmail": "e-postanız"
  },
  "vi-VN": {
    "signInTitle": "Đăng nhập vào Pioni",
    "emailOrUsername": "Email hoặc tên người dùng",
    "password": "Mật khẩu",
    "forgotPasswordOrUsername": "Quên {password} hoặc {username}?",
    "passwordLink": "mật khẩu",
    "usernameLink": "tên người dùng",
    "continue": "Tiếp tục",
    "or": "Hoặc",
    "signInWithGoogle": "Đăng nhập bằng Google",
    "signInWithX": "Đăng nhập bằng X",
    "noAccount": "Chưa có tài khoản?",
    "signUpLink": "Đăng ký",
    "createAccount": "Tạo tài khoản",
    "createAccountTitle": "Tạo tài khoản",
    "signUpSubtitle": "Truy cập paper trading trên Pioni",
    "email": "Email",
    "signUpWithGoogle": "Đăng ký bằng Google",
    "signUpWithX": "Đăng ký bằng X",
    "hasAccount": "Đã có tài khoản?",
    "signInLink": "Đăng nhập",
    "verifyEmailBlurb": "Nhập mã xác minh chúng tôi đã gửi tới {email}.",
    "verificationCode": "Mã xác minh",
    "verifyEmail": "Xác minh email",
    "useDifferentEmail": "Dùng email khác",
    "forgotTitle": "Quên mật khẩu",
    "forgotBlurb": "Nhập địa chỉ email của bạn. Nếu đúng, chúng tôi sẽ gửi email hướng dẫn đặt lại mật khẩu.",
    "forgotResetBlurb": "Nhập mã từ email và chọn mật khẩu mới.",
    "sendEmail": "Gửi email",
    "resetCode": "Mã đặt lại",
    "newPassword": "Mật khẩu mới",
    "resetPassword": "Đặt lại mật khẩu",
    "checkEmailForCode": "Kiểm tra email để nhận mã đặt lại",
    "back": "Quay lại",
    "contactSupport": "Liên hệ hỗ trợ",
    "privacyNotice": "Thông báo quyền riêng tư",
    "termsOfService": "Điều khoản dịch vụ",
    "showPassword": "Hiện mật khẩu",
    "hidePassword": "Ẩn mật khẩu",
    "language": "Ngôn ngữ",
    "needsSecondFactor": "Tài khoản này cần xác minh bổ sung",
    "couldntSignIn": "Không thể đăng nhập. Thử lại",
    "couldntVerify": "Không thể xác minh email. Thử lại",
    "couldntReset": "Không thể đặt lại mật khẩu. Thử lại",
    "yourEmail": "email của bạn"
  },
  "ms-MY": {
    "signInTitle": "Log masuk ke Pioni",
    "emailOrUsername": "E-mel atau nama pengguna",
    "password": "Kata laluan",
    "forgotPasswordOrUsername": "Lupa {password} atau {username}?",
    "passwordLink": "kata laluan",
    "usernameLink": "nama pengguna",
    "continue": "Teruskan",
    "or": "Atau",
    "signInWithGoogle": "Log masuk dengan Google",
    "signInWithX": "Log masuk dengan X",
    "noAccount": "Belum mempunyai akaun?",
    "signUpLink": "Daftar",
    "createAccount": "Cipta Akaun",
    "createAccountTitle": "Cipta akaun",
    "signUpSubtitle": "Akses paper trading di Pioni",
    "email": "E-mel",
    "signUpWithGoogle": "Daftar dengan Google",
    "signUpWithX": "Daftar dengan X",
    "hasAccount": "Sudah mempunyai akaun?",
    "signInLink": "Log masuk",
    "verifyEmailBlurb": "Masukkan kod pengesahan yang kami hantar ke {email}.",
    "verificationCode": "Kod pengesahan",
    "verifyEmail": "Sahkan e-mel",
    "useDifferentEmail": "Gunakan e-mel lain",
    "forgotTitle": "Lupa kata laluan",
    "forgotBlurb": "Masukkan alamat e-mel anda. Jika betul, kami akan menghantar e-mel dengan arahan penetapan semula kata laluan.",
    "forgotResetBlurb": "Masukkan kod dari e-mel anda dan pilih kata laluan baharu.",
    "sendEmail": "Hantar e-mel",
    "resetCode": "Kod tetapan semula",
    "newPassword": "Kata laluan baharu",
    "resetPassword": "Tetapkan semula kata laluan",
    "checkEmailForCode": "Semak e-mel anda untuk kod tetapan semula",
    "back": "Kembali",
    "contactSupport": "Hubungi Sokongan",
    "privacyNotice": "Notis Privasi",
    "termsOfService": "Syarat Perkhidmatan",
    "showPassword": "Tunjukkan kata laluan",
    "hidePassword": "Sembunyikan kata laluan",
    "language": "Bahasa",
    "needsSecondFactor": "Pengesahan tambahan diperlukan untuk akaun ini",
    "couldntSignIn": "Tidak dapat melengkapkan log masuk. Cuba lagi",
    "couldntVerify": "Tidak dapat mengesahkan e-mel. Cuba lagi",
    "couldntReset": "Tidak dapat menetapkan semula kata laluan. Cuba lagi",
    "yourEmail": "e-mel anda"
  },
  "el-GR": {
    "signInTitle": "Σύνδεση στο Pioni",
    "emailOrUsername": "Email ή όνομα χρήστη",
    "password": "Κωδικός πρόσβασης",
    "forgotPasswordOrUsername": "Ξεχάσατε τον {password} ή το {username};",
    "passwordLink": "κωδικό",
    "usernameLink": "όνομα χρήστη",
    "continue": "Συνέχεια",
    "or": "Ή",
    "signInWithGoogle": "Σύνδεση με Google",
    "signInWithX": "Σύνδεση με X",
    "noAccount": "Δεν έχετε λογαριασμό;",
    "signUpLink": "Εγγραφή",
    "createAccount": "Δημιουργία λογαριασμού",
    "createAccountTitle": "Δημιουργία λογαριασμού",
    "signUpSubtitle": "Πρόσβαση στο paper trading στο Pioni",
    "email": "Email",
    "signUpWithGoogle": "Εγγραφή με Google",
    "signUpWithX": "Εγγραφή με X",
    "hasAccount": "Έχετε ήδη λογαριασμό;",
    "signInLink": "Σύνδεση",
    "verifyEmailBlurb": "Εισαγάγετε τον κωδικό επαλήθευσης που στείλαμε στο {email}.",
    "verificationCode": "Κωδικός επαλήθευσης",
    "verifyEmail": "Επαλήθευση email",
    "useDifferentEmail": "Χρήση άλλου email",
    "forgotTitle": "Ξέχασα τον κωδικό",
    "forgotBlurb": "Εισαγάγετε τη διεύθυνση email σας. Αν είναι σωστή, θα σας στείλουμε email με οδηγίες επαναφοράς κωδικού.",
    "forgotResetBlurb": "Εισαγάγετε τον κωδικό από το email σας και επιλέξτε νέο κωδικό πρόσβασης.",
    "sendEmail": "Αποστολή email",
    "resetCode": "Κωδικός επαναφοράς",
    "newPassword": "Νέος κωδικός",
    "resetPassword": "Επαναφορά κωδικού",
    "checkEmailForCode": "Ελέγξτε το email σας για κωδικό επαναφοράς",
    "back": "Πίσω",
    "contactSupport": "Επικοινωνία με υποστήριξη",
    "privacyNotice": "Δήλωση απορρήτου",
    "termsOfService": "Όροι υπηρεσίας",
    "showPassword": "Εμφάνιση κωδικού",
    "hidePassword": "Απόκρυψη κωδικού",
    "language": "Γλώσσα",
    "needsSecondFactor": "Απαιτείται πρόσθετη επαλήθευση για αυτόν τον λογαριασμό",
    "couldntSignIn": "Αδυναμία ολοκλήρωσης σύνδεσης. Δοκιμάστε ξανά",
    "couldntVerify": "Αδυναμία επαλήθευσης email. Δοκιμάστε ξανά",
    "couldntReset": "Αδυναμία επαναφοράς κωδικού. Δοκιμάστε ξανά",
    "yourEmail": "το email σας"
  },
  "ru-RU": {
    "signInTitle": "Вход в Pioni",
    "emailOrUsername": "Эл. почта или имя пользователя",
    "password": "Пароль",
    "forgotPasswordOrUsername": "Забыли {password} или {username}?",
    "passwordLink": "пароль",
    "usernameLink": "имя пользователя",
    "continue": "Продолжить",
    "or": "Или",
    "signInWithGoogle": "Войти через Google",
    "signInWithX": "Войти через X",
    "noAccount": "Нет аккаунта?",
    "signUpLink": "Зарегистрироваться",
    "createAccount": "Создать аккаунт",
    "createAccountTitle": "Создать аккаунт",
    "signUpSubtitle": "Доступ к paper trading на Pioni",
    "email": "Эл. почта",
    "signUpWithGoogle": "Регистрация через Google",
    "signUpWithX": "Регистрация через X",
    "hasAccount": "Уже есть аккаунт?",
    "signInLink": "Войти",
    "verifyEmailBlurb": "Введите код подтверждения, отправленный на {email}.",
    "verificationCode": "Код подтверждения",
    "verifyEmail": "Подтвердить эл. почту",
    "useDifferentEmail": "Использовать другую эл. почту",
    "forgotTitle": "Забыли пароль",
    "forgotBlurb": "Введите адрес эл. почты. Если он верный, мы отправим письмо с инструкциями по сбросу пароля.",
    "forgotResetBlurb": "Введите код из письма и выберите новый пароль.",
    "sendEmail": "Отправить письмо",
    "resetCode": "Код сброса",
    "newPassword": "Новый пароль",
    "resetPassword": "Сбросить пароль",
    "checkEmailForCode": "Проверьте эл. почту — там код сброса",
    "back": "Назад",
    "contactSupport": "Связаться с поддержкой",
    "privacyNotice": "Уведомление о конфиденциальности",
    "termsOfService": "Условия обслуживания",
    "showPassword": "Показать пароль",
    "hidePassword": "Скрыть пароль",
    "language": "Язык",
    "needsSecondFactor": "Для этого аккаунта требуется дополнительная проверка",
    "couldntSignIn": "Не удалось войти. Попробуйте снова",
    "couldntVerify": "Не удалось подтвердить эл. почту. Попробуйте снова",
    "couldntReset": "Не удалось сбросить пароль. Попробуйте снова",
    "yourEmail": "вашу эл. почту"
  },
  "uk-UA": {
    "signInTitle": "Вхід у Pioni",
    "emailOrUsername": "Ел. пошта або ім'я користувача",
    "password": "Пароль",
    "forgotPasswordOrUsername": "Забули {password} чи {username}?",
    "passwordLink": "пароль",
    "usernameLink": "ім'я користувача",
    "continue": "Продовжити",
    "or": "Або",
    "signInWithGoogle": "Увійти через Google",
    "signInWithX": "Увійти через X",
    "noAccount": "Немає облікового запису?",
    "signUpLink": "Зареєструватися",
    "createAccount": "Створити обліковий запис",
    "createAccountTitle": "Створити обліковий запис",
    "signUpSubtitle": "Доступ до paper trading на Pioni",
    "email": "Ел. пошта",
    "signUpWithGoogle": "Реєстрація через Google",
    "signUpWithX": "Реєстрація через X",
    "hasAccount": "Уже маєте обліковий запис?",
    "signInLink": "Увійти",
    "verifyEmailBlurb": "Введіть код підтвердження, надісланий на {email}.",
    "verificationCode": "Код підтвердження",
    "verifyEmail": "Підтвердити ел. пошту",
    "useDifferentEmail": "Використати іншу ел. пошту",
    "forgotTitle": "Забули пароль",
    "forgotBlurb": "Введіть адресу ел. пошти. Якщо вона правильна, ми надішлемо лист з інструкціями для скидання пароля.",
    "forgotResetBlurb": "Введіть код з листа та виберіть новий пароль.",
    "sendEmail": "Надіслати лист",
    "resetCode": "Код скидання",
    "newPassword": "Новий пароль",
    "resetPassword": "Скинути пароль",
    "checkEmailForCode": "Перевірте ел. пошту — там код скидання",
    "back": "Назад",
    "contactSupport": "Зв'язатися з підтримкою",
    "privacyNotice": "Повідомлення про конфіденційність",
    "termsOfService": "Умови обслуговування",
    "showPassword": "Показати пароль",
    "hidePassword": "Сховати пароль",
    "language": "Мова",
    "needsSecondFactor": "Для цього облікового запису потрібна додаткова перевірка",
    "couldntSignIn": "Не вдалося увійти. Спробуйте ще раз",
    "couldntVerify": "Не вдалося підтвердити ел. пошту. Спробуйте ще раз",
    "couldntReset": "Не вдалося скинути пароль. Спробуйте ще раз",
    "yourEmail": "вашу ел. пошту"
  },
  "ko-KR": {
    "signInTitle": "Pioni에 로그인",
    "emailOrUsername": "이메일 또는 사용자 이름",
    "password": "비밀번호",
    "forgotPasswordOrUsername": "{password} 또는 {username}을(를) 잊으셨나요?",
    "passwordLink": "비밀번호",
    "usernameLink": "사용자 이름",
    "continue": "계속",
    "or": "또는",
    "signInWithGoogle": "Google로 로그인",
    "signInWithX": "X로 로그인",
    "noAccount": "계정이 없으신가요?",
    "signUpLink": "가입",
    "createAccount": "계정 만들기",
    "createAccountTitle": "계정 만들기",
    "signUpSubtitle": "Pioni에서 페이퍼 트레이딩을 이용하세요",
    "email": "이메일",
    "signUpWithGoogle": "Google로 가입",
    "signUpWithX": "X로 가입",
    "hasAccount": "이미 계정이 있으신가요?",
    "signInLink": "로그인",
    "verifyEmailBlurb": "{email}(으)로 보낸 인증 코드를 입력하세요.",
    "verificationCode": "인증 코드",
    "verifyEmail": "이메일 인증",
    "useDifferentEmail": "다른 이메일 사용",
    "forgotTitle": "비밀번호 찾기",
    "forgotBlurb": "이메일 주소를 입력하세요. 올바른 경우 비밀번호 재설정 안내 이메일을 보내드립니다.",
    "forgotResetBlurb": "이메일로 받은 코드를 입력하고 새 비밀번호를 선택하세요.",
    "sendEmail": "이메일 보내기",
    "resetCode": "재설정 코드",
    "newPassword": "새 비밀번호",
    "resetPassword": "비밀번호 재설정",
    "checkEmailForCode": "재설정 코드가 담긴 이메일을 확인하세요",
    "back": "뒤로",
    "contactSupport": "고객지원 문의",
    "privacyNotice": "개인정보 고지",
    "termsOfService": "서비스 약관",
    "showPassword": "비밀번호 표시",
    "hidePassword": "비밀번호 숨기기",
    "language": "언어",
    "needsSecondFactor": "이 계정에는 추가 인증이 필요합니다",
    "couldntSignIn": "로그인할 수 없습니다. 다시 시도하세요",
    "couldntVerify": "이메일을 인증할 수 없습니다. 다시 시도하세요",
    "couldntReset": "비밀번호를 재설정할 수 없습니다. 다시 시도하세요",
    "yourEmail": "이메일"
  },
  "zh-CN": {
    "signInTitle": "登录 Pioni",
    "emailOrUsername": "邮箱或用户名",
    "password": "密码",
    "forgotPasswordOrUsername": "忘记{password}或{username}？",
    "passwordLink": "密码",
    "usernameLink": "用户名",
    "continue": "继续",
    "or": "或",
    "signInWithGoogle": "使用 Google 登录",
    "signInWithX": "使用 X 登录",
    "noAccount": "还没有账户？",
    "signUpLink": "注册",
    "createAccount": "创建账户",
    "createAccountTitle": "创建账户",
    "signUpSubtitle": "在 Pioni 使用模拟交易",
    "email": "邮箱",
    "signUpWithGoogle": "使用 Google 注册",
    "signUpWithX": "使用 X 注册",
    "hasAccount": "已有账户？",
    "signInLink": "登录",
    "verifyEmailBlurb": "请输入我们发送至 {email} 的验证码。",
    "verificationCode": "验证码",
    "verifyEmail": "验证邮箱",
    "useDifferentEmail": "使用其他邮箱",
    "forgotTitle": "忘记密码",
    "forgotBlurb": "请输入您的邮箱地址。如果正确，我们将发送重置密码说明邮件。",
    "forgotResetBlurb": "请输入邮件中的验证码并设置新密码。",
    "sendEmail": "发送邮件",
    "resetCode": "重置验证码",
    "newPassword": "新密码",
    "resetPassword": "重置密码",
    "checkEmailForCode": "请查收邮件中的重置验证码",
    "back": "返回",
    "contactSupport": "联系支持",
    "privacyNotice": "隐私声明",
    "termsOfService": "服务条款",
    "showPassword": "显示密码",
    "hidePassword": "隐藏密码",
    "language": "语言",
    "needsSecondFactor": "此账户需要额外验证",
    "couldntSignIn": "无法完成登录。请重试",
    "couldntVerify": "无法验证邮箱。请重试",
    "couldntReset": "无法重置密码。请重试",
    "yourEmail": "您的邮箱"
  },
  "zh-TW": {
    "signInTitle": "登入 Pioni",
    "emailOrUsername": "電子郵件或使用者名稱",
    "password": "密碼",
    "forgotPasswordOrUsername": "忘記{password}或{username}？",
    "passwordLink": "密碼",
    "usernameLink": "使用者名稱",
    "continue": "繼續",
    "or": "或",
    "signInWithGoogle": "使用 Google 登入",
    "signInWithX": "使用 X 登入",
    "noAccount": "還沒有帳戶？",
    "signUpLink": "註冊",
    "createAccount": "建立帳戶",
    "createAccountTitle": "建立帳戶",
    "signUpSubtitle": "在 Pioni 使用模擬交易",
    "email": "電子郵件",
    "signUpWithGoogle": "使用 Google 註冊",
    "signUpWithX": "使用 X 註冊",
    "hasAccount": "已有帳戶？",
    "signInLink": "登入",
    "verifyEmailBlurb": "請輸入我們傳送至 {email} 的驗證碼。",
    "verificationCode": "驗證碼",
    "verifyEmail": "驗證電子郵件",
    "useDifferentEmail": "使用其他電子郵件",
    "forgotTitle": "忘記密碼",
    "forgotBlurb": "請輸入您的電子郵件地址。如果正確，我們將傳送重設密碼說明郵件。",
    "forgotResetBlurb": "請輸入郵件中的驗證碼並設定新密碼。",
    "sendEmail": "傳送郵件",
    "resetCode": "重設驗證碼",
    "newPassword": "新密碼",
    "resetPassword": "重設密碼",
    "checkEmailForCode": "請查收郵件中的重設驗證碼",
    "back": "返回",
    "contactSupport": "聯絡支援",
    "privacyNotice": "隱私權聲明",
    "termsOfService": "服務條款",
    "showPassword": "顯示密碼",
    "hidePassword": "隱藏密碼",
    "language": "語言",
    "needsSecondFactor": "此帳戶需要額外驗證",
    "couldntSignIn": "無法完成登入。請重試",
    "couldntVerify": "無法驗證電子郵件。請重試",
    "couldntReset": "無法重設密碼。請重試",
    "yourEmail": "您的電子郵件"
  }
};

export function authMessage(
  language: AppLanguage,
  key: AuthMessageKey,
  vars?: Record<string, string>,
): string {
  const table = AUTH_CATALOG[language] ?? enUS;
  let value = table[key] ?? enUS[key];
  if (vars) {
    for (const [name, replacement] of Object.entries(vars)) {
      value = value.split(`{${name}}`).join(replacement);
    }
  }
  return value;
}
